In [11]:
import pandas as pd
data = pd.read_csv(r'data/supply_chain_data.csv')
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [12]:
data['Location'][1]

'Mumbai'

In [13]:
data.iloc[10]

Product type                  skincare
SKU                              SKU10
Price                        15.707796
Availability                        11
Number of products sold            996
Revenue generated          2330.965802
Customer demographics       Non-binary
Stock levels                        51
Lead times                          13
Order quantities                    80
Shipping times                       2
Shipping carriers            Carrier C
Shipping costs                8.673211
Supplier name               Supplier 5
Location                       Kolkata
Lead time                           18
Production volumes                 830
Manufacturing lead time              5
Manufacturing costs          96.527353
Inspection results                Pass
Defect rates                  1.727314
Transportation modes              Road
Routes                         Route B
Costs                       806.103178
Name: 10, dtype: object

In [14]:
data.iloc[-100]

Product type                  haircare
SKU                               SKU0
Price                        69.808006
Availability                        55
Number of products sold            802
Revenue generated          8661.996792
Customer demographics       Non-binary
Stock levels                        58
Lead times                           7
Order quantities                    96
Shipping times                       4
Shipping carriers            Carrier B
Shipping costs                2.956572
Supplier name               Supplier 3
Location                        Mumbai
Lead time                           29
Production volumes                 215
Manufacturing lead time             29
Manufacturing costs          46.279879
Inspection results             Pending
Defect rates                   0.22641
Transportation modes              Road
Routes                         Route B
Costs                       187.752075
Name: 0, dtype: object

iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10

MANIPILATING THE INDEX

In [30]:
data.loc[(data['Location'] == 'Mumbai') & (data['Shipping costs'] >= 2)]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
27,cosmetics,SKU27,92.557361,42,352,2686.457224,Unknown,47,9,62,...,Mumbai,25,291,4,10.528245,Fail,2.864668,Sea,Route B,762.459182
28,cosmetics,SKU28,2.397275,12,394,6117.324615,Female,48,15,24,...,Mumbai,13,171,7,59.429382,Fail,0.815757,Air,Route A,123.437028
38,cosmetics,SKU38,52.075931,75,705,9692.318040,Non-binary,69,1,88,...,Mumbai,10,841,12,5.930694,Pending,0.613327,Air,Route B,339.672870
43,haircare,SKU43,11.743272,6,598,5737.425599,Unknown,36,29,85,...,Mumbai,1,206,23,26.277366,Pending,0.372305,Air,Route A,716.044120
48,haircare,SKU48,76.035544,28,29,7397.071005,Non-binary,30,16,9,...,Mumbai,9,109,18,23.126364,Fail,1.698113,Rail,Route B,768.651914
52,skincare,SKU52,98.031830,1,820,9435.762609,Male,64,11,11,...,Mumbai,10,727,27,9.166849,Pending,2.122472,Air,Route C,602.898499
60,skincare,SKU60,17.028028,16,380,8864.084350,Female,41,27,72,...,Mumbai,29,929,24,87.213058,Fail,2.853091,Rail,Route A,430.169097
62,cosmetics,SKU62,72.796354,89,270,3899.746834,Unknown,86,2,40,...,Mumbai,13,751,14,21.048643,Pass,1.874001,Sea,Route C,320.846516
67,skincare,SKU67,87.755432,16,513,9473.798033,Unknown,12,9,71,...,Mumbai,10,198,11,7.057876,Pass,0.131955,Sea,Route C,169.271801
78,haircare,SKU78,6.306883,50,946,1292.458418,Unknown,5,4,51,...,Mumbai,25,858,21,71.126515,Pending,4.096881,Sea,Route C,323.592203
82,skincare,SKU82,17.034931,13,336,2943.381868,Unknown,42,19,72,...,Mumbai,6,955,26,4.465278,Pending,4.137877,Road,Route C,589.978556
88,cosmetics,SKU88,75.270407,58,737,9444.742033,Male,60,18,85,...,Mumbai,21,953,11,68.184919,Pending,0.722204,Sea,Route A,103.916248
92,cosmetics,SKU92,47.714233,44,276,2100.129755,Male,90,25,10,...,Mumbai,4,671,29,62.612690,Pass,0.333432,Rail,Route B,230.092783
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423

In [32]:
data.loc[(data['Location'] == 'Delhi') | (data['Shipping costs'] >= 2)]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,haircare,SKU93,69.290831,88,114,4531.402134,Unknown,63,17,66,...,Chennai,21,824,20,35.633652,Fail,4.165782,Air,Route A,823.523846
94,cosmetics,SKU94,3.037689,97,987,7888.356547,Unknown,77,26,72,...,Delhi,12,908,14,60.387379,Pass,1.463607,Rail,Route B,846.665257
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423

In [35]:
data.loc[data['Location'].isin(['Mumbai', 'Bangalore'])]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
13,skincare,SKU13,16.160393,5,249,4052.738416,Male,80,8,48,...,Bangalore,23,173,10,97.829050,Pending,1.631074,Road,Route B,547.241005
15,skincare,SKU15,36.989245,94,469,5442.086785,Non-binary,9,8,69,...,Bangalore,14,580,7,97.121282,Pass,2.264406,Sea,Route B,127.861800
16,skincare,SKU16,7.547172,74,280,6453.797968,Female,2,5,78,...,Bangalore,3,399,21,77.106342,Pass,1.012563,Air,Route A,865.525780
24,haircare,SKU24,4.156308,32,209,9049.077861,Male,4,26,2,...,Bangalore,28,447,3,40.382360,Pending,3.691310,Air,Route A,758.724773
26,haircare,SKU26,97.446947,9,353,3716.493326,Male,59,16,48,...,Bangalore,26,171,4,15.972230,Pass,2.119320,Rail,Route A,617.866916
27,cosmetics,SKU27,92.557361,42,352,2686.457224,Unknown,47,9,62,...,Mumbai,25,291,4,10.528245,Fail,2.864668,Sea,Route B,762.459182
28,cosmetics,SKU28,2.397275,12,394,6117.324615,Female,48,15,24,...,Mumbai,13,171,7,59.429382,Fail,0.815757,Air,Route A,123.437028
38,cosmetics,SKU38,52.075931,75,705,9692.318040,Non-binary,69,1,88,...,Mumbai,10,841,12,5.930694,Pending,0.613327,Air,Route B,339.672870
42,skincare,SKU42,46.529168,98,155,1839.609426,Female,22,27,57,...,Bangalore,26,179,7,96.422821,Fail,4.939255,Road,Route A,635.657121
43,haircare,SKU43,11.743272,6,598,5737.425599,Unknown,36,29,85,...,Mumbai,1,206,23,26.277366,Pending,0.372305,Air,Route A,716.044120
48,haircare,SKU48,76.035544,28,29,7397.071005,Non-binary,30,16,9,...,Mumbai,9,109,18,23.126364,Fail,1.698113,Rail,Route B,768.651914
51,haircare,SKU51,26.700761,61,154,9866.465458,Male,100,4,52,...,Bangalore,18,673,28,14.190328,Pending,1.772951,Road,Route A,694.982318
52,skincare,SKU52,98.031830,1,820,9435.762609,Male,64,11,11,...,Mumbai,10,727,27,9.166849,Pending,2.122472,Air,Route C,602.898499
56,skincare,SKU56,20.986386,90,93,4767.020484,Non-binary,25,23,83,...,Mumbai,24,826,28,12.836285,Pass,1.173755,Air,Route B,832.210809
60,skincare,SKU60,17.028028,16,380,8864.084350,Female,41,27,72,...,Mumbai,29,929,24,87.213058,Fail,2.853091,Rail,Route A,430.169097
62,cosmetics,SKU62,72.796354,89,270,3899.746834,Unknown,86,2,40,...,Mumbai,13,751,14,21.048643,Pass,1.874001,Sea,Route C,320.846516
63,skincare,SKU63,13.017377,55,246,4256.949141,Non-binary,54,19,10,...,Bangalore,18,736,10,20.075004,Pending,3.632843,Sea,Route A,687.286178
67,skincare,SKU67,87.755432,16,513,9473.798033,Unknown,12,9,71,...,Mumbai,10,198,11,7.057876,Pass,0.131955,Sea,Route C,169.271801
68,haircare,SKU68,37.931812,29,163,3550.218433,Non-binary,0,8,58,...,Bangalore,2,375,18,97.113582,Fail,1.983468,Rail,Route A,299.706303
70,haircare,SKU70,47.914542,90,32,7014.887987,Female,10,12,22,...,Bangalore,22,775,16,11.440782,Pass,1.830576,Road,Route C,183.272899
71,cosmetics,SKU71,6.381533,14,637,8180.337085,Female,76,2,26,...,Bangalore,2,258,10,30.661677,Pending,2.078751,Road,Route A,405.167068
72,cosmetics,SKU72,90.204428,88,478,2633.121981,Non-binary,57,29,77,...,Bangalore,21,152,11,55.760493,Pending,3.213330,Rail,Route B,677.944570
76,haircare,SKU76,69.108800,23,241,5328.375984,Male,38,1,22,...,Bangalore,25,985,24,64.323598,Pending,2.180037,Rail,Route A,997.413450
78,haircare,SKU78,6.306883,50,946,1292.458418,Unknown,5,4,51,...,Mumbai,25,858,21,71.126515,Pending,4.096881,Sea,Route C,323.592203
79,haircare,SKU79,57.057031,56,198,7888.723268,Non-binary,31,25,20,...,Bangalore,5,228,12,57.870903,Pending,0.165872,Air,Route C,351.504219
82,skincare,SKU82,17.034931,13,336,2943.381868,Unknown,42,19,72,...,Mumbai,6,955,26,4.465278,Pending,4.137877,Road,Route C,589.978556
83,haircare,SKU83,68.911246,82,663,2411.754632,Unknown,65,24,7,...,Bangalore,20,443,5,97.730594,Fail,0.773006,Road,Route A,682.971018
86,skincare,SKU86,19.998177,18,223,1229.591029,Unknown,32,14,22,...,Mumbai,4,569,18,74.608970,Pass,2.051513,Rail,Route A,264.254890
88,cosmetics,SKU88,75.270407,58,737,9444.742033,Male,60,18,85,...,Mumbai,21,953,11,68.184919,Pending,0.722204,Sea,Route A,103.916248
90,skincare,SKU90,13.881914,56,320,9592.633570,Non-binary,66,18,96,...,Bangalore,8,585,8,85.675963,Pass,1.219382,Rail,Route B,990.078473
92,cosmetics,SKU92,47.714233,44,276,2100.129755,Male,90,25,10,...,Mumbai,4,671,29,62.612690,Pass,0.333432,Rail,Route B,230.092783
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423

In [36]:
data.loc[data['Routes'].notnull()]

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

SUMMARY FUNCTIONS AND MAPPING

In [40]:
data.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [41]:
data.Price.mean()

np.float64(49.462461344643685)

In [42]:
data.Location.unique()

array(['Mumbai', 'Kolkata', 'Delhi', 'Bangalore', 'Chennai'], dtype=object)

In [43]:
data.Location.value_counts()

Location
Kolkata      25
Mumbai       22
Chennai      20
Bangalore    18
Delhi        15
Name: count, dtype: int64

In [44]:
data['Customer demographics'].value_counts()

Customer demographics
Unknown       31
Female        25
Non-binary    23
Male          21
Name: count, dtype: int64

A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values

In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later

In [48]:
data_Revenue_generated_mean = data['Revenue generated'].mean()


data['Revenue generated'].map(lambda p: p - data_Revenue_generated_mean)

#Your code calculates the mean revenue and then applies a lambda function to subtract this mean from each value in the 'Revenue generated' column.

0     2885.948605
1     1684.851878
2     3801.701438
3     1990.788238
4    -3089.543036
         ...
95    1610.315757
96    1922.376578
97   -1405.131607
98    2749.904372
99    3409.137642
Name: Revenue generated, Length: 100, dtype: float64

GROUPING AND SORTING

In [50]:
data.groupby('Customer demographics')['Customer demographics'].count()

Customer demographics
Female        25
Male          21
Non-binary    23
Unknown       31
Name: Customer demographics, dtype: int64

Getting the least(minimum) number of products sold

In [53]:
data.groupby("Product type")['Number of products sold'].min()

Product type
cosmetics    25
haircare      8
skincare     65
Name: Number of products sold, dtype: int64

In [55]:
data.groupby("Product type")['Number of products sold'].max()

Product type
cosmetics    987
haircare     946
skincare     996
Name: Number of products sold, dtype: int64

where are the most products appearing in the most

In [59]:
data.groupby('Product type')['Location'].max()

Product type
cosmetics    Mumbai
haircare     Mumbai
skincare     Mumbai
Name: Location, dtype: object

In [ ]:
data.groupby('Location').apply(lambda df: df.SKU.iloc[0])

#The apply() function operates on each group (i.e., each subset of data that belongs to a unique Location).

#The lambda function selects the first SKU (df.SKU.iloc[0]) from each group.

C:\Users\windows 10\AppData\Local\Temp\ipykernel_8928\4238272393.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data.groupby('Location').apply(lambda df: df.SKU.iloc[0])

Location
Bangalore    SKU5
Chennai      SKU9
Delhi        SKU4
Kolkata      SKU3
Mumbai       SKU0
dtype: object

SORTING

Number of products sold in each country

In [65]:
data.groupby('Location')['Shipping costs'].mean().sort_by('Location',ascending == False)

AttributeError: 'Series' object has no attribute 'sort_by'